package com.ledgeros.infrastructure.exception;

public enum ExceptionCode {
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    EMAIL_NOT_VERIFIED,
    USER_NOT_FOUND,
    INVALID_VERIFICATION_CODE,
    VERIFICATION_CODE_EXPIRED,
    INVALID_RESET_CODE,
    RESET_CODE_EXPIRED,
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_REFRESH_TOKEN,
    INVALID_REFRESH_TOKEN_ID,
    REFRESH_TOKEN_EXPIRED,
    INTERNAL_SERVER_ERROR;

    public int getStatusCode() {
        return switch (this) {
            case INVALID_REQUEST, INVALID_REFRESH_TOKEN_ID, INVALID_VERIFICATION_CODE, VERIFICATION_CODE_EXPIRED, INVALID_RESET_CODE, RESET_CODE_EXPIRED -> 400;
            case UNAUTHORIZED, INVALID_CREDENTIALS, INVALID_REFRESH_TOKEN, REFRESH_TOKEN_EXPIRED -> 401;
            case FORBIDDEN, EMAIL_NOT_VERIFIED -> 403;
            case USER_NOT_FOUND -> 404;
            case EMAIL_ALREADY_EXISTS -> 409;
            default -> 500;
        };
    }
}
